version = "1.0"

[main]
name = "Main Settings"
services = ["__APP__"]

    [main.permissions]
    name = "Permissions for using the bridge"

        [main.permissions.helptext]
        ask = '''
        Roles with Increasing Power: Relay<User<Admin
        Allowed values for roles:
        - * : All Matrix users
        - domain.tld : All users on a given homeserver
        - mxid (@user:matrix.org) : Specific Matrix user
        '''
        type = "markdown"

        [main.permissions.listrelay]
        ask = "Users bridged thanks to Relay Mode"
        type = "tags"
        help = "Relay Role: Talk on WhatsApp through the RelayBot in a room where it has been activated with '!wa set-relay', no access otherwise."
        visible = "enable_relaybot"

        [main.permissions.listuser]
        ask = "Bridge Users"
        type = "tags"
        help = "User Role: Access to use the bridge to chat with a WhatsApp account."

        [main.permissions.listadmin]
        ask = "Bridge Administrators"
        type = "tags"
        help = "Admin Role: User level and some additional administration tools."

    [main.bridge]
    name = "Puppetting Bridge Settings"

        [main.bridge.enable_relaybot]
        ask = "Should Relay Mode be allowed?"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "If allowed, '!wa set-relay' can be used to turn any Bridge User into a RelayBot for that chat. This allows people to talk on WhatsApp without an own account."
        bind = "relay>enabled:__FINALPATH__/config.yaml"


    [main.bot]
    name = "Robot Settings"

        [main.bot.botname]
        ask = "Username of the AppService Bot"
        type = "string"
        help = "Sets bot username. Please keep in mind that the bot admin room for previous bot username will stop working so you may need to create a new one using the new username"
        bind = "bot>username:__FINALPATH__/config.yaml"

        [main.bot.displayname]
        ask = "Display name for Bot"
        type = "string"
        help = "Set to 'remove' to remove display name, leave empty to set default 'WhatsApp bridge bot'"
        bind = ":__FINALPATH__/config.yaml"

        [main.bot.avatar]
        ask = "Avatar for Bot"
        type = "string"
        help = "Should be in format 'mxc://server_name/NeXNQarUbrlYBiPCpprYsRqr', see README for tutorial. Set to 'remove' to remove avatar, leave empty to use standard Skype logo."
        bind = ":__FINALPATH__/config.yaml"

[privacy]
name = "Privacy"
services = ["__APP__"]

    [privacy.portal_rooms]
    name = "Portal Rooms & Encryption Settings"

        [privacy.portal_rooms.text]
        ask = '''
        !! Inviting the Bridge in an encrypted room          !!
        !! breaks real End-to-End Encryption (e2ee)          !! 
        !! Messages will be unencrypted on the Bridge Server !!
        '''
        type = "markdown"

        [privacy.portal_rooms.encryption]
        ask = "Allow Encryption between Matrix Client and Bridge Server?"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Enable so-called End-to-Bridge (e2b) Encryption. For the Bridge to work in group chat Rooms with End-to-End Encryption (e2ee) enabled."
        bind = "encryption>allow:__FINALPATH__/config.yaml"
        
        [privacy.portal_rooms.encryption_default]
        ask = "Force-enable Encryption in all Portal Rooms the Bridge creates?"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "This will cause the Bridge Bot to be in private chats for the Encryption to work properly."
        bind = "encryption>default:__FINALPATH__/config.yaml"
        visible = "encryption"

    [privacy.config]
    name = "Privacy Settings"

        [privacy.config.delivery_receipts]
        ask = "Enable Delivery Receipts?"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Should the bridge send a read Receipt from the bridge bot when a message has been sent to WhatsApp?"
        bind = ":__FINALPATH__/config.yaml"


[advanced]
name = "Advanced Settings"
services = ["__APP__"]

    [advanced.help]
    name = "SETTINGS FOR EXPERTS IN SERVER ADMINISTRATION"

        [advanced.help.text]
        ask = "!! There are **security and privacy risks** if you change these settings without knowing what you do !!"
        type = "markdown"

    [advanced.whatsapp]
    name = "WhatsApp Web API MetaData"

        [advanced.whatsapp.username_template]
        ask = "Localpart template of MXIDs for WhatsApp users"
        type = "string"
        help = "Defaults to 'skype_{{.}}'. '{{.}}' is replaced with the phone number 'msidsn' of the WhatsApp user."
        bind = ":__FINALPATH__/config.yaml"

    [advanced.appservice]
    name = "HomeServer Application Service"

        [advanced.appservice.print_level]
        ask = "Logging print level for Standard Output"
        type = "select"
        choices = ["debug", "info", "warn", "error", "fatal"]
        help = "Minimum severity for log messages printed to stdout/stderr. This doesn't affect the log file."
        bind = ":__FINALPATH__/config.yaml"
